-- SELECT *,
-- ORDERSELLINGPRICE - ORDERCOSTPRICE AS ORDERPROFIT
-- FROM RAW.GLOBALMART.ORDERS

-- SELECT *,
-- ORDERSELLINGPRICE - ORDERCOSTPRICE AS ORDERPROFIT
-- FROM {{ ref('raw_orders') }}

SELECT
O.ORDERID,
O.ORDERDATE,
O.SHIPDATE,
O.SHIPMODE,
O.ORDERSELLINGPRICE - O.ORDERCOSTPRICE AS ORDERPROFIT,
O.ORDERSELLINGPRICE,
O.ORDERCOSTPRICE,
C.CUSTOMERNAME,
C.SEGMENT,
C.COUNTRY,
P.CATEGORY,
P.PRODUCTNAME,
P.SUBCATEGORY
FROM {{ ref('raw_orders') }} AS O
LEFT JOIN
{{ ref('raw_customers') }} AS C
ON O.CUSTOMERID=C.CUSTOMERID
LEFT JOIN
{{ ref('raw_products') }} AS P
ON O.PRODUCTID=P.PRODUCTID